#58 settings page - first draft
joshua-lehmann/SmashGrade pull request #107
Opened 2023-12-10 19:20 UTC by JasminKeller

# PR: First Draft of Settings Page

Beschreibung:
- New Setting Page added
- Added useUserProfile as Hook
- language switch / LocalProvider moved into settings page

closes #57 

Examples: 
![image](https://github.com/SmashGrade/SmashGrade-App/assets/111414152/ed0b1fa0-72bc-46bb-a51f-1c21d5021987)
![image](https://github.com/SmashGrade/SmashGrade-App/assets/111414152/527a296e-9101-413a-be80-20fcd6f9b812)

2023-12-16 08:00 UTC, joshua-lehmann commented
Die Navigation "klebt" nun etwas weit oben:
Vorher:
![image](https://github.com/SmashGrade/SmashGrade-App/assets/23728611/299c7e86-faa1-4251-a116-56cb16ccd1fb)
Nacher:
![image](https://github.com/SmashGrade/SmashGrade-App/assets/23728611/36c206ca-be03-4363-88fe-d2b0d77e2c56)

2024-01-09 14:16 UTC, joshua-lehmann requested changes

2024-01-09 14:16 UTC, joshua-lehmann commented on api/tsconfig.json
> +    // "verbatimModuleSyntax": true,                     /* Do not transform or elide any imports or exports not marked as type-only, ensuring they are written in the output file's format based on th
Wahrscheinlich unbeabsichtigt?

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/profile/UserProfile.tsx
> -                {/*Initials are a fallback for profile picture (for example if no picture is found)*/}
Ich glaube der Kommentar ist hilfreich, würde ihn lassen :)

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/profile/UserProfile.tsx
> +    if (isLoading || pictureLoading) return <Spin />;
Wenn hier wie vorher auf undefined geprüft wird, muss unten nicht immer mit userProfile? gearbeitet werden

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/settings/Settings.tsx
> + */
Kommentierter Code entfernen oder wieder enablen

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/settings/Settings.tsx
> +    if (isLoading) return <p>Laden...</p>;
Antd <Spin> Komponente verwenden

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/settings/Settings.tsx
> +                    <p>max.placeholder@hftm.ch</p>
Das userProfile gibt auch eine Mail zurück, die du anzeigen kannst:
![image](https://github.com/SmashGrade/SmashGrade-App/assets/23728611/fda27597-c489-4a1e-82be-3cfacb07a22c)

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/settings/Settings.tsx
> +                Meine Module
Übersetzen

2024-01-09 14:16 UTC, joshua-lehmann commented on src/features/settings/Settings.tsx
> +                    <div className={styles.title}>Sprache</div>
Übersetzen

2024-01-09 14:16 UTC, joshua-lehmann commented on src/i18n/ReactIntlProvider.tsx
> +// import { IntlProvider as IntlProviderCustom } from 'react-intl';
entfernen falls nicht benötigt

2024-01-11 12:17 UTC, JasminKeller commented on api/tsconfig.json
> +    // "verbatimModuleSyntax": true,                     /* Do not transform or elide any imports or exports not marked as type-only, ensuring they are written in the output file's format based on th
jup, kein plan was ich da gemacht hab ^^ ist schon zu lange her. hab es wieder auf setting umbenannt ist ja nur ein kommentar

2024-01-11 12:19 UTC, JasminKeller commented on src/features/profile/UserProfile.tsx
> -                {/*Initials are a fallback for profile picture (for example if no picture is found)*/}
danke für den hinweis. hab ich wieder hinzugefügt.

2024-01-11 12:24 UTC, JasminKeller commented on src/features/profile/UserProfile.tsx
> +    if (isLoading || pictureLoading) return <Spin />;
|| pictureLoading und     isLoading: pictureLoading, wurde entfernt

2024-01-11 12:25 UTC, JasminKeller commented on src/features/settings/Settings.tsx
> + */
kommentar vorerst entfernt.

2024-01-11 12:27 UTC, JasminKeller commented on src/features/settings/Settings.tsx
> +    if (isLoading) return <p>Laden...</p>;
Ist angepasst. Antd Komponente wird nun verwendet:
if (isLoading) return <Spin />;

2024-01-11 12:29 UTC, JasminKeller commented on src/i18n/ReactIntlProvider.tsx
> +// import { IntlProvider as IntlProviderCustom } from 'react-intl';
wurde entfernt

2024-01-11 12:38 UTC, JasminKeller commented on src/features/settings/Settings.tsx
> +                    <p>max.placeholder@hftm.ch</p>
Ist angepasst.

2024-01-11 12:57 UTC, JasminKeller commented on src/features/settings/Settings.tsx
> +                Meine Module
Done

2024-01-11 12:57 UTC, JasminKeller commented on src/features/settings/Settings.tsx
> +                    <div className={styles.title}>Sprache</div>
Done

2024-01-11 14:47 UTC, joshua-lehmann approved these changes

2024-01-12 11:46 UTC, merged