#111 module overview
joshua-lehmann/SmashGrade pull request #112
Opened 2024-01-05 14:21 UTC by wanjabachmann

# How-To Create a PR (Delete this section before saving PR)
1. Add a descriptive title

2. Add a description
   -  Quickly explain what you did 
   - **Must include:** *closes #[issueNumber]* (this will auto link the PR to the issue and close it after PR is merged)
3. Make sure all Sonar Cloud issues are resolved
4. Make sure the GitHub Pipeline checks are all successful
5. Make sure you tested your change locally and it works as expected
6. After your PR is ready assign someone  in the "Reviewer" field, you can also add 2 people if you think it make sense for your change
7. After the review is done
   - If there are no changes requested and the PR is approved you can continue with step 7
   - If there are change requests, do them, push the branch and start again from step 3 and add a comment tagging the reviewer, letting him know you did all requested changes
8. Merge your PR
9. Add a comment tagging @Testing team where you explain how your change can be tested and if possible, include a URL directly to the feature on the TEST System

# PR: 

Beschreibung:
Module Overview Page on the Course Admin area.

* Created a new GridView with Search Function and a Submenu to edit, delete and copy an existing entry. (Thats the reason why I don't use the Grid.tsx)
* Implemented the needed JSON API entries for testing.
* Implemented GET Request
* Implemented DELETE Request --> Not final yet and needs review.

closes #xx

2024-01-07 14:31 UTC, wanjabachmann commented
@joshua-lehmann zwei Punkte:
1. Haben wir irgendwo schon ein Delete API Request als Beispiel? 
2. Soll ich das Submenü welches bei Sonar Cloud bemängelt wird mittels Button lösen und entsprechend via SCSS "umstylen"?
https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&pullRequest=112&id=SmashGrade_SmashGrade-App

2024-01-09 16:28 UTC, joshua-lehmann commented
> @joshua-lehmann zwei Punkte:
> 
> 1. Haben wir irgendwo schon ein Delete API Request als Beispiel?
> 2. Soll ich das Submenü welches bei Sonar Cloud bemängelt wird mittels Button lösen und entsprechend via SCSS "umstylen"?
>    https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&pullRequest=112&id=SmashGrade_SmashGrade-App

@wanjabachmann  Für den Delete request, haben wir noch nicht aber du musst eine mutation verwenden, du kannst dir mein Beispiel hier anschauen: https://github.com/SmashGrade/SmashGrade-App/pull/115/files#diff-2d06ed8547a15c78bf8efc90cb72aa1ea020fbbb61f1ced6605f0610f57b05caR27 & 
https://github.com/SmashGrade/SmashGrade-App/pull/115/files#diff-08483d303f7b590414aba509cdd5e4ca6382b36448ebeaf2d5e40b43b51e7fe2R42
Du musst aber natürlich anstelle wie ich ein PUT ein DELETE axios request verwenden, aber der "Mutation" part sollte sehr ähnlich sein.

Für das submenu werde ich mir noch anschauen bin noch nich dazu gekommen.

2024-01-09 19:55 UTC, wanjabachmann commented
> > @joshua-lehmann zwei Punkte:
> > 
> > 1. Haben wir irgendwo schon ein Delete API Request als Beispiel?
> > 2. Soll ich das Submenü welches bei Sonar Cloud bemängelt wird mittels Button lösen und entsprechend via SCSS "umstylen"?
> >    https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&pullRequest=112&id=SmashGrade_SmashGrade-App
> 
> @wanjabachmann Für den Delete request, haben wir noch nicht aber du musst eine mutation verwenden, du kannst dir mein Beispiel hier anschauen: https://github.com/SmashGrade/SmashGrade-App/pull/115/files#diff-2d06ed8547a15c78bf8efc90cb72aa1ea020fbbb61f1ced6605f0610f57b05caR27 & https://github.com/SmashGrade/SmashGrade-App/pull/115/files#diff-08483d303f7b590414aba509cdd5e4ca6382b36448ebeaf2d5e40b43b51e7fe2R42 Du musst aber natürlich anstelle wie ich ein PUT ein DELETE axios request verwenden, aber der "Mutation" part sollte sehr ähnlich sein.
> 
> Für das submenu werde ich mir noch anschauen bin noch nich dazu gekommen.

Habe ich mal so implementiert und die Element schonmal durch Buttons ersetzt um das Quality Gate zu erreichen.

2024-01-11 14:41 UTC, joshua-lehmann requested changes
Habe das grid gefixt, gibt aber noch paar kleine Dinge zum ändern.

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +}
Bitte in eigenes moduleApi.ts verschieben

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +        if (window.confirm('Wirklich Löschen?')) {
Bitte antd Popconfirm verwenden: https://ant.design/components/popconfirm

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +
entweder fixen oder löschen

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +
Bitte unter components einen Folder "grid" machen und dort für jeden CellRenderer ein eigenes File machen (für wiederverwendung)

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +    const onFilterInputChange: React.ChangeEventHandler<HTMLInputElement> = (e) => {
Die "zwischen Funktion ist nicht nötig, einfach direkt deine onFilterTextBoxChanged" verwenden und dort das even akzeptieren.

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +                <CopyOutlined />{' '}
`{' '}` entfernen

2024-01-11 14:41 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +                <CopyOutlined />{' '}
`{' '}` entfernen

2024-01-12 06:14 UTC, wanjabachmann commented on src/features/module/ModuleList.tsx
> +        if (window.confirm('Wirklich Löschen?')) {
Idee an sich gut, aber da das  Submenü immer irgendwo geöffnet wird etwas umständlich:
![Antd-Popconfirm](https://github.com/SmashGrade/SmashGrade-App/assets/54718339/c16cbe42-6f11-4fe1-847b-2cc5e6128f8b)

Wäre die Verwendung eines Modal allenfalls besser geeignet?
https://ant.design/components/modal

2024-01-12 06:16 UTC, wanjabachmann commented on src/features/module/ModuleList.tsx
> +
Kannst du allenfalls nochmals prüfen, ob ich das richtig umgesetzt habe? Bin nicht ganz sicher, ob ich das richtig verstanden habe. Ansonsten können wür ja evtl auch heute NM oder Morgen kurz schauen.

2024-01-12 15:20 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +        if (window.confirm('Wirklich Löschen?')) {
Man kann das pop confirm richtig platzieren, indem man es um den effektiven delete button platziert. Aber da du ein dropdown Menü verwendest und dies nach dem Klicken weg geht würde es trotzdem komisch aussehen. Also von dem her kannst du gut ein Modal verwenden.

2024-01-12 15:21 UTC, joshua-lehmann commented on src/features/module/ModuleList.tsx
> +
Ja sieht soweit okay aus

2024-01-12 15:22 UTC, joshua-lehmann approved these changes

2024-01-13 18:01 UTC, wanjabachmann commented
everything merged into dev

2024-01-13 18:04 UTC, merged