#8 Add I18N
joshua-lehmann/SmashGrade pull request #28
Opened 2023-10-15 14:53 UTC by theGreyPilgrim42

# Open PR Steps
3. Make sure all Sonar Cloud issues are resolved
4. Make sure the GitHub Pipeline checks are all successful
5. Make sure you tested your change locally and it works as expected
6. After your PR is ready assign someone  in the "Reviewer" field, you can also add 2 people if you think it make sense for your change
7. After the review is done
   - If there are no changes requested and the PR is approved you can continue with step 7
   - If there are change requests, do them, push the branch and start again from step 3 and add a comment tagging the reviewer, letting him know you did all requested changes
8. Merge your PR
9. Add a comment tagging @Testing team where you explain how your change can be tested and if possible, include a URL directly to the feature on the TEST System

# PR: 

Beschreibung:
This PR adds FormatJS for I18N and add a basic LocaleSwitcher.

closes #8

2023-10-16 09:45 UTC, joshua-lehmann requested changes
I already implemented some of the changes I suggested. But please check the parts about the extract/compile scripts and the docs

2023-10-16 09:45 UTC, joshua-lehmann commented on package.json
> +        "compile": "formatjs compile"
I think you need to change it like this:

```suggestion
        "extract": "formatjs extract \"src/**/*.{ts,tsx}\" --ignore \"**/*.d.ts\"",
        "compile": "formatjs compile \"src/**/*.{ts,tsx}\" --ignore \"**/*.d.ts\""
```
otherwise I get an error when running the commands
Also maybe you need to specify the output files for the languages I am not sure?

2023-10-16 09:45 UTC, joshua-lehmann commented on src/App.tsx
> +        <IntlProvider locale={locale} messages={messages} defaultLocale={defaultLocale}>
Please do this in the `main.tsx` and wrap the whole App component like suggested in the docs.
https://formatjs.io/docs/react-intl/#creating-an-i18n-context

2023-10-16 09:45 UTC, joshua-lehmann commented on tsconfig.json
The docs also mention some compiler options which should be set? Maybe we should do it?
![image](https://github.com/SmashGrade/SmashGrade-App/assets/23728611/9fe4e7af-1ba9-45cb-b5ab-c65e65195ada)

2023-10-16 09:45 UTC, joshua-lehmann commented on package.json
Please also add an explanation how to use those scripts and how to generate and compile the translation for all three languages. Either do it in the GitHub Wiki and link it in the readme or describe it directly in the readme. So that everyone is able to use the format js cli commands on his/her own.

2023-10-16 09:45 UTC, joshua-lehmann commented on src/App.tsx
> +    const defaultLocale = navigator.language ? navigator.language : locales.de;
You can simplify it with [Nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)

```suggestion
    const defaultLocale = navigator.language ?? locales.de;
```

2023-10-16 09:45 UTC, joshua-lehmann commented on src/i18n/languages.ts
> +};
```suggestion
type Locale = 'de' | 'en' | 'fr';

export const locales: Record<Locale, Locale> = {
    de: 'de',
    en: 'en',
    fr: 'fr',
};

export const languages: Record<Locale, Record<string, string>> = {
    de: de,
    en: en,
    fr: fr,
};
```

2023-10-16 18:59 UTC, theGreyPilgrim42 commented on src/App.tsx
> +    const defaultLocale = navigator.language ? navigator.language : locales.de;
Thanks for the input :)

2023-10-16 19:22 UTC, theGreyPilgrim42 commented on src/App.tsx
> +        <IntlProvider locale={locale} messages={messages} defaultLocale={defaultLocale}>
I'm honestly kinda stuck here. @joshua-lehmann  Is there a way to manage state in the main.tsx file?

2023-10-16 19:26 UTC, theGreyPilgrim42 commented on tsconfig.json
Already done.

2023-10-16 19:52 UTC, theGreyPilgrim42 commented on package.json
Added a short description to the README

2023-10-16 19:53 UTC, theGreyPilgrim42 commented on package.json
> +        "compile": "formatjs compile"
Added specific scripts for the different supported languages

2023-10-17 08:39 UTC, joshua-lehmann commented on src/App.tsx
> +        <IntlProvider locale={locale} messages={messages} defaultLocale={defaultLocale}>
@theGreyPilgrim42 I created a separate component to achieve it.

2023-10-17 08:42 UTC, joshua-lehmann approved these changes
@theGreyPilgrim42 I implemented some changes, mainly to achieve full type saftey and auto complete for both locales and message ID's (so that inside the `formatMessage()` or the `<FormattedMessage/>` you can only use message id's which exists. 
In addition I also made an optimization to load the langue file async to allow code splitting and only loading the language file which is needed. I used [the code here ](https://github.com/formatjs/formatjs/tree/main/packages/react-intl/examples/StaticTypeSafetyAndCodeSplitting) as inspiration.
Please quickly check my changes and if there is nothing that you disagree you can merge.

2023-10-17 08:44 UTC, joshua-lehmann commented on package.json
Thanks for the description. We also need to think about if we need to integrate this in our CI/CD Pipeline or how to handle the translation in general in the future.

2023-10-17 20:09 UTC, merged