#42 module overview
joshua-lehmann/SmashGrade pull request #79
Opened 2023-11-08 16:24 UTC by robinaeschlimann

# PR: 42 - Module overview for students

Description:
- Added module page
- Added tabs to switch between the studies
- Fetched modules and courses from the api
- Styled the overview page

closes #42

2023-11-09 09:59 UTC, joshua-lehmann requested changes
Some small changes requested, but all in all looks good!

2023-11-09 09:59 UTC, joshua-lehmann commented on src/pages/routes/routes.ts
> +    path: '/modules/',
`/` at the start/end are ignored in paths and added automatically by the router, so you can remove them

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Modules.tsx
> +        <>
remove react fragment

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Modules.tsx
> +};
In general we should avoid creating functions to return JSX. Either do the map function inline in directly on the module.children prop, or create an own react component like ModuleCourses, but in this case I think you can do it inline on line 49.
https://stackoverflow.com/questions/64769304/advantages-of-rendering-a-component-vs-a-function-returning-jsx-react

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Modules.tsx
> +        queryKey: ['StudentModules' + activeFilter],
```suggestion
queryKey: ['studentModules', activeFilter],
```
Query keys should use an array element for each "part" of the key. Also we used camelCase for all keys so we should continue that.
https://tanstack.com/query/v5/docs/react/guides/query-keys#array-keys-with-variables

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Modules.tsx
> +    return modules && modules.length > 0 ? (
Can be simplified like this:
```suggestion
 return  modules?.length ? (
```
Explanation: If modules is falsy (null, undefined) it the ? mark operator will already check and return false. Then we check the length, and since the number 0 is a falsy value it would also return false so no need to use the greater than operator.

https://developer.mozilla.org/en-US/docs/Glossary/Falsy
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Rating.module.scss
> +        padding: 2px 10px 2px 10px;
```suggestion
padding: 2px 10px;
```
First value is vertical, second horizontal padding

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Rating.module.scss
> +        padding: 2px 10px 2px 10px;
```suggestion
margin: 0 10px;
```

2023-11-09 09:59 UTC, joshua-lehmann commented on src/features/student/modules/Rating.tsx
> +};
I personally think a switch would be more readable
```suggestion
const getRatingClass = (rating: number) => {
    switch (true) {
        case rating <= 0:
            return RATING_CLASSNAMES.none;
        case rating < 4:
            return RATING_CLASSNAMES.bad;
        case rating < 5:
            return RATING_CLASSNAMES.median;
        default:
            return RATING_CLASSNAMES.good;
    }
};
```

2023-11-10 18:10 UTC, JasminKeller commented
@robinaeschlimann 
Ich habe dazu auch noch ein Feedback. Ich sehe deine neue Page ist nun zu "Module" gelinkt in der Navigation, jedoch gehört es zu "Mein Studium" (Mobile Studenten Ansicht). 
Der Menu Punkt Module ist dann für den Kursadmin. 
Sry dachte das war klar im letzen Meeting. 
Falls es immernoch nicht klar ist kann ich es morgen nochmals erklären :)

2023-11-11 08:39 UTC, robinaeschlimann commented
@joshua-lehmann i've pushed your small change requests. Please have a look and approve my PR

2023-11-11 09:17 UTC, joshua-lehmann approved these changes
All comments are solved and looks good 👍

2023-11-11 10:49 UTC, merged